### ISSUE TITLE
ros2 node list doesn't work with containers

### ISSUE THREAD

**Issue by Aposhian** [ros2/rmw_fastrtps#615]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- Installation type:
  - binaries
- Version or commit hash:
  - 5.0.2-1focal.20220430.124017
- DDS implementation:
  - Fast-RTPS
- Client library (if applicable):
  - rclcpp and rclpy

#### Steps to reproduce issue

Here is a Dockerfile
```Dockerfile
FROM ros:galactic
RUN apt-get update && apt-get install -y \
    ros-$ROS_DISTRO-demo-nodes-cpp \
    ros-$ROS_DISTRO-rmw-fastrtps-cpp \
    ros-$ROS_DISTRO-rmw-cyclonedds-cpp
```
and a compose file
```yaml
services:
  talker:
    build: ./
    command: ros2 run demo_nodes_cpp talker
    network_mode: host
    ipc: host
    environment:
      - RMW_IMPLEMENTATION
      - ROS_DOMAIN_ID
```
Run the following test script:
```bash
#!/usr/bin/env bash

source /opt/ros/galactic/setup.bash

run_node_and_check() {
    export RMW_IMPLEMENTATION=$1
    ros2 daemon stop &> /dev/null
    docker-compose down &> /dev/null
    docker-compose up -d &> /dev/null
    echo "$RMW_IMPLEMENTATION node list:"
    ros2 node list
}

run_node_and_check rmw_cyclonedds_cpp

run_node_and_check rmw_fastrtps_cpp
```

#### Expected behavior
```
rmw_cyclonedds_cpp node list:
/talker
rmw_fastrtps_cpp node list:
/talker
```

#### Actual behavior
```
rmw_cyclonedds_cpp node list:
/talker
rmw_fastrtps_cpp node list:
```

**Comment by Aposhian** [comment]
If I run `ros2 node list` in another container, then it works, on both `galactic` and `humble` images.
```yaml
services:
  talker:
    build: ./
    command: ros2 run demo_nodes_cpp talker
    network_mode: host
    ipc: host
    environment:
      - RMW_IMPLEMENTATION
      - ROS_DOMAIN_ID
  lister:
    build: ./
    command: ros2 node list
    network_mode: host
    ipc: host
    environment:
      - RMW_IMPLEMENTATION
      - ROS_DOMAIN_ID
    depends_on:
      - talker
```
