### ISSUE TITLE
Running a subscriber on Humble with publishing from Jazzy / Rolling uses up all memory

### ISSUE THREAD

**Issue by urfeex** [ros2/rmw_fastrtps#797]
## Bug report

While I am aware that inter-distribution traffic isn't supported, I would at least expect systems not to crash if that occurs. However, we noticed that running both, Humble and Jazzy nodes on the same network can cause the machines running Humble nodes to run out of memory, probably because of discovery traffic. It is sufficient to have a Humble subscriber and do a `ros2 topic list` from Jazzy to (sometimes) trigger the issue.

**Required Info:**

- Operating System: Ubuntu 22.04 / 24.04
- Installation type: binary
- Version or commit hash: latest
- DDS implementation:
  - default -> fastrtps
- Client library (if applicable):
  - Checked using rclpy

#### Steps to reproduce issue
The following docker-compose file illustrates the issue. **Running this will make your system run out of memory!!!**

```
---
version: '2'

networks:
  rosdocker:
    driver: bridge

services:
  talker:
    image: ros:jazzy
    container_name: lister
    hostname: lister
    networks:
      - rosdocker
    environment:
      - "ROS_DOMAIN_ID=13"
    command: "ros2 topic list"
    restart: always  # It seems not to happen every time, hence the restart

  listener:
    image: ros:humble
    container_name: listener
    hostname: listener
    networks:
      - rosdocker
    environment:
      - "ROS_DOMAIN_ID=13"
    command: "ros2 topic echo /chatter std_msgs/String"
```

#### Expected behavior
Error messages, silent ignores, or magically just work. Note: As said earlier, I do not expect cross-distro communication to simply work, but I would expect stable behavior.

#### Actual behavior
The `ros2 topic echo` seems to cause unlimited memory consumption and makes the system run OOM in a matter of seconds.

#### Additional information

- We haven't investigated things further down RMW code, but we do see the error output caught in https://github.com/ros2/rmw_fastrtps/pull/737 on the humble node.
- I have tried the same thing with rmw_cyclone_cpp which throws warnings on the `list` and errors on the `echo` but doesn't crash or end up in OOM. So, this seems to be a rmw_fastrtps_cpp issue.
